name: Release new version
# Triggered by a new release on Github
# - create new pypi package

on:
  release:
    types: [published]

jobs:
  create_wheels:
    # Create pypi package
    uses: ./.github/workflows/create_wheel.yml
    secrets: inherit


  upload_pypi:
    # Upload pypi package
    needs: [create_wheels]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/bibtex-dblp
      # When testing
      #name: testpypi
      #url: https://test.pypi.org/p/bibtex-dblp
    permissions:
      id-token: write
    # Only upload if using original repo and triggered by either a release or a manual workflow dispatch
    if: ${{ github.repository_owner == 'volkm' && ((github.event_name == 'release' && github.event.action == 'published') || github.event_name == 'workflow_dispatch') }}
    steps:
      - uses: actions/download-artifact@v7
        with:
          path: dist
          merge-multiple: true
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # When testing
          #repository-url: https://test.pypi.org/legacy/
          verbose: true
          skip-existing: true
